### ISSUE TITLE
Tests timing out when failed and diffing big strings

### ISSUE THREAD

**Issue by michallepicki** [exercism/gleam-test-runner#23]
Steps to reproduce:
1. Open the [Twelve Days exercise](https://exercism.org/tracks/gleam/exercises/twelve-days) editor
2. Paste the [example solution](https://github.com/exercism/gleam/blob/main/exercises/practice/twelve-days/.meta/example.gleam)
3. Make a small typo change, e.g. "eighth" -> "eight" on line 37
4. Run tests

This is probably caused by a performance issue in [gap](https://github.com/JohnBjrk/gap)

**Comment by lpil** [comment]
I've removed diffing for now and opened an issue with gap for the performance issue.
