### ISSUE TITLE
exercism_test_runner 1.2.0 cannot compile under gleam 0.29.0

### ISSUE THREAD

**Issue by sseg** [exercism/gleam-test-runner#24]
I was trying to load and test an exercise with `gleam test`. Its gleam.toml looks like this:

```
name = "accumulate"
version = "0.1.0"

[dependencies]
gleam_stdlib = "~> 0.29"
gleam_bitwise = "~> 1.2"

[dev-dependencies]
exercism_test_runner = "~> 1.2"
```

Trying to run the tests spits out this syntax error:
```
  Compiling exercism_test_runner
error: Syntax error
   ┌─ /Users/sseg/Exercism/gleam/accumulate/build/packages/exercism_test_runner/src/exercism/test_runner.gleam:58:1
   │
58 │ @external(erlang, "file", "list_dir")
   │ ^ I can't figure out what to do with this character.
```

Is looks like the issue might actually date from 1.1.0? https://github.com/exercism/gleam-test-runner/commit/f51b8d7bd53fcce69b9094f2cd2ce59a0525f8f3

@lpil is this expected?

**Comment by lpil** [comment]
Hi @sseg !! Sorry about this, the new test runner required v0.30.0 or higher.
