### ISSUE TITLE
Tests are unexpectedly slow

### ISSUE THREAD

**Issue by ee7** [exercism/gleam-test-runner#4]
Follow-up to https://github.com/exercism/gleam-test-runner/issues/3#issuecomment-1317721846 and https://github.com/exercism/gleam-test-runner/pull/2#pullrequestreview-1180387820.

Any ideas for speeding things up?

**Comment by iHiD** [comment]
I know nothing about Gleam, but a quick Google tells me it's BEAM-based, so it might need the same treatment as Elixir to speed it up, specifically an entry identical to this adding in this file: https://github.com/exercism/tooling-invoker/blob/main/tools.json#L2-L5

---

Note for Erik: To test this in production is a little tricky - it might be worth us isolating a specific machine somehow to do this on. However, if you can get it performing faster in your local setup with those changes, we can probably be confident they'll transmit into production, so the isolation might be unnecessary.

**Comment by ErikSchierboom** [comment]
I was able to verify the improved speed locally: https://github.com/exercism/tooling-invoker/pull/58

**Comment by iHiD** [comment]
OK, so @lpil - this is a weird one :)

What we discovered is that for most tracks it's most effective not to have a network device attached to the machine. However, for BEAM, we discovered that when there's no network device, BEAN sits there for ~5secs wondering what to do (I presume it's in a retry loop). However, if there is a network device, but it has no external connectivity then it happily accepts that and just moves on.

That LOC that Erik added is what changes that 🙂

**Comment by iHiD** [comment]
> Has the change propagated to production? 

The change propagates as each machine is built, and every machine is rebuilt every 24hrs (old machines die after about 36hrs of running due to docker imploding with how many containers we start/stop on them). So it'll take 24hrs to get across the fleet.

> And is the speed in production meaningful before a track is launched?

Yes, it runs on the same system.

**Comment by lpil** [comment]
Ah that makes sense, I understand now. Erlang is designed for distributed computing so when you boot the VM the first thing it does is open a port so that it can be joined to a cluster of Erlang nodes. It'll have been hanging at this step.
