### ISSUE TITLE
An Error Occurred: There was a problem when running the shell command `escript`.

### ISSUE THREAD

**Issue by zanddev** [exercism/gleam-test-runner#65]
Four my submissions
* ex [sublist](https://exercism.org/tracks/gleam/exercises/sublist) ‒ [all three iterations](https://exercism.org/tracks/gleam/exercises/sublist/solutions/ZandDev)
* ex [matching-brackets](https://exercism.org/tracks/gleam/exercises/matching-brackets) ‒ [iteration 5](https://exercism.org/tracks/gleam/exercises/matching-brackets/solutions/ZandDev) 
* ex [tracks-on-tracks-on-tracks](https://exercism.org/tracks/gleam/exercises/tracks-on-tracks-on-tracks) ‒ [iteration 1](https://exercism.org/tracks/gleam/exercises/tracks-on-tracks-on-tracks/solutions/ZandDev)
* ex [raindrops](https://exercism.org/tracks/gleam/exercises/raindrops) ‒ [iteration 1](https://exercism.org/tracks/gleam/exercises/raindrops/solutions/ZandDev)

made the test_runner generate this error:

![Schermata del 2024-05-08 19-13-33](https://github.com/exercism/gleam-test-runner/assets/35665697/1e2651d7-63ec-44fd-a8b9-18425b5ac091)

when the tests of each submission were executed on exercism. Locally they work perfectly.

**Comment by lpil** [comment]
Hello! What version of Gleam are you using?

**Comment by zanddev** [comment]
You quickly found the source of the problem. I'm using Gleam v. 1.1.0. But is it bugged on Exercism (locally it isn't) or am I wrong when using it?

**Comment by lpil** [comment]
The error message is not useful, I agree. I just happen to remember that there was an issue with this pattern.
