### ISSUE TITLE
Extend or replace exercism/should for test cases?

### ISSUE THREAD

**Issue by jimmux** [exercism/gleam-test-runner#82]
This is perhaps more of a question than an issue, as I'm sure this must have been considered already.

I was working on an exercise where the feedback from failed tests wasn't as informative as it could be, due to using `let assert` instead of `should.equal`. I was going to submit a pull request to fix this for any exercises that would benefit, and noticed that many test cases are just comparing boolean results so the benefit would be minimal. The feedback to the user could be more user friendly if `exercism/should` also had `be_true`, `be_false`, `be_error`, `be_ok`, etc. like `gleeunit/should` does.

Is it a goal to avoid dependencies on any particular unit test libraries? If so, is there any reason to not add a few more comparison functions to `exercism/should`? I'd be happy to update test cases either way if this is an option.

**Comment by lpil** [comment]
This is intentional and in future should will be deprecated and removed altogether due to it having less debug information. If you search you may be able to find the previous discussion.

**Comment by jimmux** [comment]
Thanks, Louis. I didn't see any discussion on it in this repo, but I expect you're referring to [this one](https://github.com/exercism/gleam/issues/148) in the main gleam repo.

If `should` is destined for deprecation then I'll resist converting any test cases.
